# Generated by Django 5.2.5 on 2025-09-06 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
        ('products', '0007_remove_priceoptimization_demand_forecast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandforecast',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='products.product'),
        ),
    ]
