# Generated by Django 5.2.5 on 2025-09-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_sale_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='customer_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
