# Generated by Django 5.2.5 on 2025-09-06 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='price_at_sale',
            new_name='selling_price',
        ),
        migrations.AlterField(
            model_name='sales',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='products.product'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='units_sold',
            field=models.IntegerField(),
        ),
    ]
