# Generated by Django 5.2.5 on 2025-09-06 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_price_at_sale_sales_selling_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
    ]
