# Generated by Django 5.2.5 on 2025-09-06 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_selling_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceoptimization',
            name='demand_forecast',
        ),
        migrations.RemoveField(
            model_name='priceoptimization',
            name='product',
        ),
        migrations.DeleteModel(
            name='DemandForecast',
        ),
        migrations.DeleteModel(
            name='PriceOptimization',
        ),
    ]
